In [1]:
import tensorflow as tf

In [2]:
train_path = r"C:\Users\HP\Downloads\Genders_Recognition\Train\Train"

In [3]:
test_path = r"C:\Users\HP\Downloads\Genders_Recognition\Test\Test"

In [4]:
from tensorflow.keras.utils import image_dataset_from_directory

In [5]:
image_size = 128
batch_size = 32

In [6]:
training_data = image_dataset_from_directory(
                train_path,
                image_size=(image_size,image_size),
                batch_size=32,
                label_mode="int") # image size must be same for all images, batch_size ->for training only 32 images processed in one time.

Found 11135 files belonging to 2 classes.


In [7]:
valid_data = image_dataset_from_directory(
             test_path,
             image_size=(image_size,image_size), 
             batch_size=32,
             label_mode="int") # image size must be same for all images, batch_size ->for training only 32 images processed in one time.)

Found 1279 files belonging to 2 classes.


In [8]:
class_name= training_data.class_names

In [9]:
print(class_name)

['Female', 'Male']


In [10]:
normalisation=tf.keras.layers.Rescaling(
              1./255
)

In [11]:
training_data = training_data.map(
    lambda x,y:(normalisation(x),y
))

In [12]:
valid_data = valid_data.map(
    lambda x,y:(normalisation(x),y
))

In [13]:
from tensorflow.keras.models import Sequential

In [14]:
from tensorflow.keras import layers

In [15]:
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense

In [16]:
model = tf.keras.Sequential()

In [19]:
# Input Layer
model.add(tf.keras.Input(shape = (128,128,3)))

# Hidden Layer
model.add(MaxPooling2D(2,2))
model.add(layers.Conv2D(64,(3,3),activation="relu"))
model.add(MaxPooling2D(2,2))
model.add(layers.Conv2D(64,(3,3),activation="relu"))
model.add(MaxPooling2D(2,2))
model.add(layers.Flatten())
model.add(layers.Dense(64,activation="relu"))

# Output Layer
model.add(layers.Dense(1,activation="sigmoid"))

In [20]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ max_pooling2d (MaxPooling2D)         │ (None, 64, 64, 3)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d (Conv2D)                      │ (None, 62, 62, 64)          │           1,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 31, 31, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 29, 29, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 14, 14, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 12544)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │         802,880 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 841,665 (3.21 MB)

 Trainable params: 841,665 (3.21 MB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.fit(training_data,epochs=10,validation_data=valid_data)

Epoch 1/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 62s 170ms/step - accuracy: 0.7153 - loss: 0.5404 - val_accuracy: 0.8170 - val_loss: 0.4166
Epoch 2/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 79s 160ms/step - accuracy: 0.8148 - loss: 0.4074 - val_accuracy: 0.8194 - val_loss: 0.3968
Epoch 3/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 57s 163ms/step - accuracy: 0.8544 - loss: 0.3349 - val_accuracy: 0.8780 - val_loss: 0.3095
Epoch 4/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 82s 164ms/step - accuracy: 0.8762 - loss: 0.2913 - val_accuracy: 0.8710 - val_loss: 0.3186
Epoch 5/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 58s 167ms/step - accuracy: 0.8984 - loss: 0.2485 - val_accuracy: 0.8819 - val_loss: 0.3024
Epoch 6/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 80s 161ms/step - accuracy: 0.9114 - loss: 0.2199 - val_accuracy: 0.8858 - val_loss: 0.3173
Epoch 7/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 55s 159ms/step - accuracy: 0.9262 - loss: 0.1843 - val_accuracy: 0.8507 - val_loss: 0.3996
Epoch 8/10
348/348 ━━━━━━━━━━━━━━━━━━━━ 55s 159ms/step - accuracy: 0.9396 - loss: 0

In [36]:
from tensorflow.keras.preprocessing import image
import numpy as np

In [37]:
img_path = r"C:\Users\HP\Downloads\Genders_Recognition\Train\Train\Female\12.png"

In [38]:
img = image.load_img(img_path,target_size=(128,128))

In [39]:
img_array = image.img_to_array(img)

In [40]:
print(img_array)

[[[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [ 28.  24.  18.]
  [ 28.  24.  18.]
  [ 21.  18.  13.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [ 22.  19.  14.]
  [ 22.  19.  14.]
  [ 14.  11.   6.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [ 22.  19.  14.]
  [ 22.  19.  14.]
  [ 14.  11.   6.]]

 ...

 [[108.  85.  57.]
  [ 94.  74.  49.]
  [ 94.  74.  49.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[108.  85.  57.]
  [ 94.  74.  49.]
  [ 94.  74.  49.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[ 95.  77.  50.]
  [ 77.  62.  37.]
  [ 77.  62.  37.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]]


In [41]:
img_array = img_array/255.0

In [42]:
img_array = np.expand_dims(img_array,axis=0)

In [43]:
print(img_array.shape)

(1, 128, 128, 3)


In [44]:
prediction = model.predict(img_array)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step


In [45]:
print(prediction)

[[4.1355157e-05]]


In [46]:
predicted_class = 1 if prediction[0][0] >= 0.5 else 0

In [47]:
print(predicted_class)

0


In [48]:
print("Predicted class",class_name[predicted_class])

Predicted class Female
